spring.application.name=git
spring.datasource.url=jdbc:mysql://localhost:3306/testdb?createDatabaseIfNotExist=true
spring.datasource.username=ragul
spring.datasource.password=${DB_PASSWORD}
server.port=9091
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#logging.level.org.springframework.core.env=DEBUG
